//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public System.Guid Id { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public string Imagen { get; set; }
        public int Precio { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Usuario { get; set; }
        public bool Activo { get; set; }
        public bool Web { get; set; }
        public string ContenidoPortugues { get; set; }
    }
}
