//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporteMorande.Models.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comision
    {
        public System.Guid Id { get; set; }
        public System.Guid IdServicio { get; set; }
        public string Nombre { get; set; }
        public int Porcentaje { get; set; }
        public int PrecioInicial { get; set; }
        public int PrecioFinal { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
