//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporteMorande.Models.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liquidacion()
        {
            this.DetalleLiquidacion = new HashSet<DetalleLiquidacion>();
        }
    
        public System.Guid Id { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Monto { get; set; }
        public string Estado { get; set; }
        public string IdVendedor { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleLiquidacion> DetalleLiquidacion { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
