//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporteMorande.Models.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public System.Guid Id { get; set; }
        public string Titulo { get; set; }
        public string Imagen { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Usuario { get; set; }
    }
}
