//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.DetalleLiquidacion = new HashSet<DetalleLiquidacion>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public Nullable<int> PaxAdulto { get; set; }
        public Nullable<int> PrecioAdulto { get; set; }
        public Nullable<int> PaxInfante { get; set; }
        public Nullable<int> PrecioInfante { get; set; }
        public Nullable<int> Total { get; set; }
        public string Observaciones { get; set; }
        public string EstadoPago { get; set; }
        public string Estado { get; set; }
        public Nullable<System.Guid> IdServicio { get; set; }
        public Nullable<bool> Cerrada { get; set; }
        public string Habitacion { get; set; }
        public Nullable<System.Guid> IdHotel { get; set; }
        public Nullable<System.Guid> IdDomicilio { get; set; }
        public string EstadoPagoEmpleador { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleLiquidacion> DetalleLiquidacion { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Domicilio Domicilio { get; set; }
    }
}
