//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_WEBAPI
    {
        public System.Guid Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Cliente { get; set; }
        public string Origen { get; set; }
        public string StackTrace { get; set; }
        public string Message { get; set; }
        public string Comentarios { get; set; }
    }
}
