//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdHotel { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Valor { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
